spring:
  application:
    name: redis-reactive-cache
  main:
    web-application-type: none
  profiles:
    active: lib
---
spring:
  config:
    activate:
      on-profile: lib
  redis:
    host: "localhost"
    port: 6379
    timeout: 5000
    client-name: ${spring.application.name}
    date_format: "dd-MM-yyyy"
    time_format: "HH:mm:ss"
